package org.aimas.ami.cmm.simulation.users;

public class UserQueryCatalog {

	public static String numUsersQuery = "" 
			+ "PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>" + "\n"
    		+ "PREFIX smartclassroom: <http://pervasive.semanticweb.org/ont/2014/07/smartclassroom#>" + "\n"
			+ "PREFIX bootstrap: <http://pervasive.semanticweb.org/ont/2014/07/smartclassroom/bootstrap#>" + "\n"
			+ "PREFIX per: <http://pervasive.semanticweb.org/ont/2004/06/person#>" + "\n"
			+ "PREFIX ctxann: <http://pervasive.semanticweb.org/ont/2014/05/consert/annotation#>" + "\n"
			+ "PREFIX functions: <http://pervasive.semanticweb.org/ont/2014/05/consert/functions#>" + "\n"
			+ "PREFIX afn: <http://jena.hpl.hp.com/ARQ/function#>" + "\n"
			
    		+ "SELECT (COUNT(DISTINCT ?user) AS ?numUsers)" + "\n"
    		+ "WHERE {" + "\n"
    		+ "	 GRAPH ?assertionID {" + "\n"
    		+ "		?user	per:locatedIn 	bootstrap:EF210" + "\n"
    		+ "	 }" + "\n"
    		+ "  GRAPH <http://pervasive.semanticweb.org/ont/2004/06/person/locatedInStore> {"
    		+ "		?assertionID ctxann:hasTimestamp ?tsAnn ."
    		+ "		?tsAnn ctxann:hasStructuredValue ?time ."
    		+ "		?assertionID ctxann:hasCertainty ?certAnn ."
    		+ "		?certAnn ctxann:hasStructuredValue ?certainty ."
    		+ "  }"
    		+ "	 FILTER ((?time >= functions:datetimeDelay(functions:now(), -2)) && (?certainty >= 0.8))"
    		+ "}"; 
	
	
	public static String usersPresentQuery = "" 
			+ "PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>" + "\n"
    		+ "PREFIX smartclassroom: <http://pervasive.semanticweb.org/ont/2014/07/smartclassroom#>" + "\n"
			+ "PREFIX bootstrap: <http://pervasive.semanticweb.org/ont/2014/07/smartclassroom/bootstrap#>" + "\n"
			+ "PREFIX per: <http://pervasive.semanticweb.org/ont/2004/06/person#>" + "\n"
			+ "PREFIX ctxann: <http://pervasive.semanticweb.org/ont/2014/05/consert/annotation#>" + "\n"
			+ "PREFIX functions: <http://pervasive.semanticweb.org/ont/2014/05/consert/functions#>" + "\n"
			+ "PREFIX afn: <http://jena.hpl.hp.com/ARQ/function#>" + "\n"
			
    		+ "ASK" + "\n"
    		+ "{" + "\n"
    		+ "	 	GRAPH ?assertionID {" + "\n"
    		+ "			?user	per:locatedIn 	bootstrap:EF210" + "\n"
    		+ "	 	}" + "\n"
    		+ "  	GRAPH <http://pervasive.semanticweb.org/ont/2004/06/person/locatedInStore> {"
    		+ "			?assertionID ctxann:hasTimestamp ?tsAnn ."
    		+ "			?tsAnn ctxann:hasStructuredValue ?time ."
    		+ "			?assertionID ctxann:hasCertainty ?certAnn ."
    		+ "			?certAnn ctxann:hasStructuredValue ?certainty ."
    		+ "  	}"
    		+ "	 	FILTER ((?time >= functions:datetimeDelay(functions:now(), -2)) && (?certainty >= 0.8))"
    		+ "}";
	
	public static String adHocMeetingQuery = ""
			+ "PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>" + "\n"
    		+ "PREFIX smartclassroom: <http://pervasive.semanticweb.org/ont/2014/07/smartclassroom#>" + "\n"
			+ "PREFIX bootstrap: <http://pervasive.semanticweb.org/ont/2014/07/smartclassroom/bootstrap#>" + "\n"
			+ "PREFIX per: <http://pervasive.semanticweb.org/ont/2004/06/person#>" + "\n"
			+ "PREFIX ctxcore: <http://pervasive.semanticweb.org/ont/2014/05/consert/core#>" + "\n"
			+ "PREFIX ctxann: <http://pervasive.semanticweb.org/ont/2014/05/consert/annotation#>" + "\n"
			+ "PREFIX functions: <http://pervasive.semanticweb.org/ont/2014/05/consert/functions#>" + "\n"
			+ "PREFIX afn: <http://jena.hpl.hp.com/ARQ/function#>" + "\n"
			
    		+ "ASK" + "\n"
    		+ "{" + "\n"
    		+ "	 GRAPH ?adhocID {" + "\n"
    		+ "		?discussion rdf:type smartclassroom:HostsAdHocDiscussion;" + "\n"
    		+ "					ctxcore:assertionRole ?roomSection." + "\n"
    		+ "	 }" + "\n"
    		+ "  GRAPH <http://pervasive.semanticweb.org/ont/2014/07/smartclassroom/HostsAdHocDiscussionStore> {"
    		+ "		?adhocID ctxann:hasTimestamp ?tsAnn ."
    		+ "		?tsAnn ctxann:hasStructuredValue ?time ."
    		+ "		?adhocID ctxann:hasCertainty ?certAnn ."
    		+ "		?certAnn ctxann:hasStructuredValue ?certainty ."
    		+ "  }"
    		+ "	 FILTER ((?time >= functions:datetimeDelay(functions:now(), -2)) && (?certainty >= 0.8))"
    		+ "}";
	
	public static String getLuminosityQuery = ""
			+ "PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>" + "\n"
    		+ "PREFIX smartclassroom: <http://pervasive.semanticweb.org/ont/2014/07/smartclassroom#>" + "\n"
			+ "PREFIX bootstrap: <http://pervasive.semanticweb.org/ont/2014/07/smartclassroom/bootstrap#>" + "\n"
			+ "PREFIX device: <http://pervasive.semanticweb.org/ont/2004/06/device#>" + "\n"
			+ "PREFIX ctxann: <http://pervasive.semanticweb.org/ont/2014/05/consert/annotation#>" + "\n"
			+ "PREFIX functions: <http://pervasive.semanticweb.org/ont/2014/05/consert/functions#>" + "\n"
			+ "PREFIX afn: <http://jena.hpl.hp.com/ARQ/function#>" + "\n"
			
    		+ "SELECT DISTINCT ?roomSection ?luminosity" + "\n"
    		+ "WHERE {" + "\n"
    		+ "	 GRAPH ?luminosityID {" + "\n"
    		+ "		?sensor	 smartclassroom:sensesLuminosity ?luminosity" + "\n"
    		+ "	 }" + "\n"
    		+ "  GRAPH <http://pervasive.semanticweb.org/ont/2014/07/smartclassroom/sensesLuminosityStore> {"
    		+ "		?luminosityID ctxann:hasTimestamp ?tsAnn ."
    		+ "		?tsAnn ctxann:hasStructuredValue ?time ."
    		+ "		?luminosityID ctxann:hasCertainty ?certAnn ."
    		+ "		?certAnn ctxann:hasStructuredValue ?certainty ."
    		+ "  }"
    		+ "	 FILTER ((?time >= functions:datetimeDelay(functions:now(), -2)) && (?certainty >= 0.8))"
    		+ "	 GRAPH ?deviceLocID {" + "\n"
    		+ "		?sensor	 device:hasProfiledLocation ?roomSection" + "\n"
    		+ "	 }" + "\n"
    		+ "}"; 
	
	public static String getTemperatureQuery = ""
			+ "PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>" + "\n"
    		+ "PREFIX smartclassroom: <http://pervasive.semanticweb.org/ont/2014/07/smartclassroom#>" + "\n"
			+ "PREFIX bootstrap: <http://pervasive.semanticweb.org/ont/2014/07/smartclassroom/bootstrap#>" + "\n"
			+ "PREFIX device: <http://pervasive.semanticweb.org/ont/2004/06/device#>" + "\n"
			+ "PREFIX ctxann: <http://pervasive.semanticweb.org/ont/2014/05/consert/annotation#>" + "\n"
			+ "PREFIX functions: <http://pervasive.semanticweb.org/ont/2014/05/consert/functions#>" + "\n"
			+ "PREFIX afn: <http://jena.hpl.hp.com/ARQ/function#>" + "\n"
			
    		+ "SELECT DISTINCT ?roomSection ?temperature" + "\n"
    		+ "WHERE {" + "\n"
    		+ "  GRAPH <http://pervasive.semanticweb.org/ont/2014/05/consert/entityStore> {"
    		+ "	 	?sensor a smartclassroom:TemperatureSensor"
    		+ "	 }"
    		+ "	 GRAPH ?temperatureID {" + "\n"
    		+ "		?sensor	 smartclassroom:sensesTemperature ?temperature" + "\n"
    		+ "	 }" + "\n"
    		+ "  GRAPH <http://pervasive.semanticweb.org/ont/2014/07/smartclassroom/sensesTemperatureStore> {"
    		+ "		?temperatureID ctxann:hasTimestamp ?tsAnn ."
    		+ "		?tsAnn ctxann:hasStructuredValue ?time ."
    		+ "		?temperatureID ctxann:hasCertainty ?certAnn ."
    		+ "		?certAnn ctxann:hasStructuredValue ?certainty ."
    		+ "  }"
    		+ "	 FILTER ((?time >= functions:datetimeDelay(functions:now(), -2)) && (?certainty >= 0.8))"
    		+ "	 GRAPH ?deviceLocID {" + "\n"
    		+ "		?sensor	 device:hasProfiledLocation ?roomSection" + "\n"
    		+ "	 }" + "\n"
    		+ "}"; 
	
}
